[server]
headless = true

[browser]
gatherUsageStats = false

# Light Theme (Standard)
[theme]
base = "light"
primaryColor = "#38bdf8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

